### ISSUE TITLE
No output after second loop

### ISSUE THREAD

**Issue by hannotify** [quarkiverse/quarkus-bon-jova-rockstar#104]
Rockstar program:

```
The walls are high and mighty
While the walls ain't nothing
Knock the walls down

Shout the walls

Finished are our hopes and dreams
Our city is in need of rebuilding
While our city is not finished
Build our city up

Shout our city
```

Satriani output:

```
0
2420
```

Bon Jova output:
```
0
```

**Comment by holly-cummins** [comment]
The good news: This is fixed. 
The bad news: I don't totally understand why, and this exact code still doesn't work in a unit test, even though it works in the integration test. Is it whitespace? EOFs? Something to do with the classloader?
